name: Run ETF Monitor Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas tushare numpy

    - name: Run ETF Monitor Script
      env:
        # 将你的 Tushare Token 设置为 GitHub Actions 的 Secrets
        # 这样可以保护你的敏感信息
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
      run: |
        python ETF.py
