name: Run ETF Monitor Script and Push Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      # 每天下午5点10分运行（UTC时区是早上9点10分）
      - cron: '10 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # 授予 Actions 写入仓库内容的权限
      contents: write

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pandas tushare numpy

    - name: 运行你的 ETF 监控脚本
      env:
        # 将你的 Tushare Token 设置为 GitHub Actions 的 Secrets
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
      run: |
        python ETF.py
        python ETF_screened.py


    - name: 提交并推送文件
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add final_filtered_funds.csv df_funds_with_metrics.csv
        git commit -m "每日数据更新" || echo "没有文件变动，跳过提交"
        git push
