name: Run ETF Screening Strategy

on:
  push:
    branches:
      - main
    paths:
      - 'ETF_screened.py'
      - 'upload_to_oss.py'
  workflow_dispatch:
  workflow_run:
    workflows: ["Update ETF Data Report"]
    types:
      - completed
    branches:
      - main

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    # 仅在 Update ETF Data Report 成功完成时运行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pandas tushare numpy
          pip install oss2

      - name: Restore data report from cache
        uses: actions/cache@v3
        with:
          path: etf_metrics_daily_report.csv
          key: ${{ runner.os }}-etf-data-report-${{ hashFiles('etf_metrics_daily_report.csv') }}
          restore-keys: |
            ${{ runner.os }}-etf-data-report-

      - name: Run ETF 策略和上传脚本
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: |
          python ETF_screened.py
          python upload_to_oss.py
