name: Run ETF Screening Strategy

on:
  push:
    branches:
      - main
    paths:
      - 'ETF_screened.py'
      - 'upload_to_oss.py'
  workflow_dispatch:

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tushare numpy
          pip install oss2

      - name: Restore data report from cache
        uses: actions/cache@v3
        with:
          path: etf_metrics_daily_report.csv
          key: ${{ runner.os }}-etf-data-report-${{ hashFiles('etf_metrics_daily_report.csv') }}
          restore-keys: |
            ${{ runner.os }}-etf-data-report-

      - name: Run ETF 策略和上传脚本
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: |
          python ETF.py
          python ETF_screened.py
          python upload_to_oss.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add etf_screener_final_report.csv
          git commit -m "Update ETF screener final report" || echo "No changes to commit"
          git push
