name: Update ETF Data Report

on:
  schedule:
    # 每天下午5点10分运行（UTC时区是早上9点10分）
    - cron: '10 9 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pandas tushare numpy
          pip install oss2

      - name: 运行 ETF 数据获取脚本
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          python ETF.py

      - name: 运行 ETF 筛选脚本
        run: python ETF_screened.py

      - name: 上传数据到OSS并缓存报告
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: |
          python upload_to_oss.py
          # 缓存 etf_metrics_daily_report.csv
          
      - name: Cache the data report
        uses: actions/cache@v3
        with:
          path: etf_metrics_daily_report.csv
          key: ${{ runner.os }}-etf-data-report-${{ hashFiles('etf_metrics_daily_report.csv') }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add etf_screener_final_report.csv
          git commit -m "Update ETF screener final report" || echo "No changes to commit"
          git push
