name: Update All ETF Data

on:
  push:
    branches:
      - main
    paths:
      - 'ETF.py'
  workflow_dispatch:
  schedule:
    - cron: '10 9 * * *'

jobs:
  full-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tushare numpy oss2

      - name: Run all scripts and upload
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: |
          python ETF.py
          python ETF_screened.py
          python upload_to_oss.py

      - name: Upload generated reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: etf-reports
          path: |
            etf_metrics_daily_report.csv
            etf_screener_final_report.csv
